run:
	docker run --name foip-chat -it -p 5000:5000 foip/chat
build:
	docker image build -t foip/chat .



# GO_SOURCE_PATH = cmd/server/main.go
# GO_BINARY_FILE = server

# all:
# 	go get

# build:
# 	go build $(GO_SOURCE_PATH) -o $(GO_BINARY_FILE)
# run-dev:
# 	env PORT=5000 \
# 	go run $(GO_SOURCE_PATH)
# run:
# 	env PORT=5000 GIN_MODE=release \
# 	go run $(GO_SOURCE_PATH)
