// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2022-10-24 17:41:11.684082964 +0900 JST m=+0.142193115
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/token": {
            "get": {
                "description": "show API documentation",
                "produces": [
                    "text/json"
                ],
                "tags": [
                    "livekit",
                    "user"
                ],
                "summary": "API Documentation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room",
                        "name": "room",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User",
                        "name": "user",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/metrics": {
            "get": {
                "description": "show metrics for prometheus",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "admin",
                    "monitoring"
                ],
                "summary": "Metrics for Prometheus",
                "responses": {}
            }
        },
        "/swagger/": {
            "get": {
                "description": "show API documentation",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "API Documentation",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
