---
server:
  port: :8080
  # https://pkg.go.dev/github.com/labstack/echo/v4@v4.8.0/middleware#CORSConfig
  cors:
    allow_origins: ["*"]
    allow_methods:
      - "GET"
      - "HEAD"
      - "PUT"
      - "PATCH"
      - "POST"
      - "DELETE"
